# Generated by Django 5.2 on 2025-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('model_type', models.CharField(choices=[('decision_tree', 'Decision Tree Classifier'), ('random_forest', 'Random Forest Classifier'), ('xgboost', 'XGBoost Classifier')], default='decision_tree', max_length=32)),
                ('file', models.FileField(upload_to='models/')),
            ],
        ),
    ]
